version: "3.7"

services:
  robot:
    env_file:
        - .env
    image: docker.pkg.github.com/jekabolt/tolya-robot/tolya-robot:latest
    # volumes:
    #   - /home/ # persistent database data.
    ports:
      - 80:8080