version: "3.3"

services:
  robot:
    env_file:
        - .env
    image: docker.pkg.github.com/jekabolt/tolya-robot/tolya-robot:latest
    # volumes:
    #   - /home/ # persistent database data.
    ports:
      - 80:8080

  mongodb_container:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/root/app/db
  # volumes:
  #   mongodb_data_container: