name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # - name: test
    #   run: go test ./...
    
    - name: Update SHA
      run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} + "kek"

